name: steps examples
on:
  workflow_dispatch
jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: Example of custom action
    steps:
    - name: Checkout Actions
      uses: actions/checkout@v2
    - id: step-caller
      uses: "./.github/actions/hello.yml"
      with:
        the-caller: 'Myself'
    - run: echo random-number ${{ steps.step-caller.outputs.random-number }}
      shell: bash
